### ISSUE TITLE
Indexing fails at "find-dataset-documents"

### ISSUE THREAD

**Issue by patrickmuston1** [opendatacube/cube-in-a-box-dea#1]
Good afternoon!

While indexing data in my local deployment I received the following error:

> Failed to list: s3://dea-public-data/L2/sentinel-2-nbar/S2MSIARD_NBAR/
> bash: line 1: /scripts/s-2-all-scenes.txt.gz: No such file or directory

This occurred while running `find-dataset-documents:` per the Makefile below.

```
# 4. Index data
index:
	docker-compose exec jupyter \
		bash -c "gunzip -c < /scripts/vic-scenes.tar.gz | dc-index-from-tar"

# Careful, this takes a very long time.
find-dataset-documents:
	docker-compose exec jupyter \
		bash -c \
			"s3-find s3://dea-public-data/L2/sentinel-2-nbar/S2MSIARD_NBAR/**/**/ARD-METADATA.yaml\
			 > /scripts/s-2-all-scenes.txt | gzip -c /scripts/s-2-all-scenes.txt | /scripts/s-2-all-scenes.txt.gz"

```

I believe `index:` executed correctly.  Looking at the scripts folder the "s-2-all-scenes.txt.gz" doesn't exist. Is this missing or have I failed at a previous step?

Thanks!

**Comment by alexgleith** [comment]
You shouldn't need to run that step, @patrickmuston1. I ran it previously, though it's probably changed around since I saved it out.

If you've run the indexing step, that's all you need to do :-)

**Comment by bluetyson** [comment]
Thanks for all this, Alex.

**Comment by patrickmuston1** [comment]
Thanks Alex, right you are - I am able to get data after the indexing step. Thanks.
